site_name: A
theme:
  name: material
  language: zh # è¯­è¨€ï¼Œé»˜è®¤ä¸ºen
  features:
    - navigation.tabs
  palette: # é¢œè‰²
    primary: indigo # ä¸»è‰²
    accent: indigo # è¾…åŠ©è‰²


nav:
  - ä¸»é¡µ: index.md
  - erlang:
      - åœ¨è¿œç¨‹èŠ‚ç‚¹ä¸Šä½¿ç”¨recon_trace: erlang/recon_trace.md
      - BeamBookç¿»è¯‘:
          - Part I:ERTS: erlang/beambook/ERTS_1.md
  - go:
      - ä»£ç ç»“æ„ä¸gomockçš„ä½¿ç”¨: go/gomock.md
  - ç®—æ³•/æ•°æ®ç»“æ„:
      - æ—¥æœŸä¸æ—¶é—´æˆ³: algorithm/timestamp.md
      - éº»å°†å‘å¬æ•°è®¡ç®—: mahjong/å‘å¬æ•°.md
      - crit bit tree: data_structure/crit_bit_tree.md
  - æ•°æ®åº“:
      - OSXä¸Šå®‰è£…PostgreSQLæ’ä»¶: database/postgresql_plugin.md
      - æ¨èåˆ—è¡¨è®¾è®¡1: database/tiplist1.md
      - æ¨èåˆ—è¡¨è®¾è®¡2: database/tiplist2.md
      - PostgreSQLæ’ä»¶å¼€å‘1: database/pg_plugin_1.md
      - æ•°æ®åº“ä¸­çš„ğŸŒ²: database/tree.md